import { renderPlayerAvatar } from './playerAvatar.js';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const show=v=>v==null||v===''?'—':esc(v);
const statusLabel={starter:'Titolare',sub:'Entrato',unused:'Inutilizzato',injured:'Infortunato',suspended:'Squalificato',replaced:'Sostituito'};
function stat(label,value){return `<div class="player-stat"><span>${label}</span><strong>${show(value)}</strong></div>`;}
export function renderPlayerPanel(player,stats,{similarId=null,similarContent=""}={}){
 const s=stats?.seasonStats||{};
 const history=(stats?.matchdays||[]).slice().sort((a,b)=>(b.matchday||0)-(a.matchday||0));
 return `<div class="player-panel-backdrop" data-close-player-panel><aside class="player-panel" role="dialog" aria-modal="true" aria-label="Scheda ${esc(player?.name||'giocatore')}"><button class="player-panel__close icon-btn" data-close-player-panel aria-label="Chiudi">×</button><header class="player-panel__header">${renderPlayerAvatar({name:player?.name,avatarUrl:stats?.avatarUrl,size:'lg'})}<div><span class="eyebrow">SCHEDA GIOCATORE</span><h2>${esc(player?.name||'')}</h2><p>${esc(player?.club||'')} · ${esc((player?.roles||stats?.roles||[]).join('/'))}</p></div></header>${similarId?`<button type="button" class="primary-btn similar-trigger" data-find-similar="${esc(similarId)}">Trova giocatori simili</button>`:""}${similarContent}${stats?`<section class="player-stats-grid">${stat('Media voto',s.averageRating)}${stat('Fantamedia',s.fantasyAverage)}${stat('Partite a voto',s.ratedMatches)}${stat('Presenze',s.appearances)}${stat('Gol',s.goals)}${stat('Assist',s.assists)}${stat('Ammonizioni',s.yellowCards)}${stat('Espulsioni',s.redCards)}${stat('Autogol',s.ownGoals)}${stat('Rigori',s.penaltiesTotal==null?'—':`${s.penaltiesScored??0}/${s.penaltiesTotal}`)}</section><section class="player-history"><div class="section-head"><div><span class="eyebrow">GIORNATE</span><h3>Storico</h3></div></div>${history.length?history.map(m=>`<details class="matchday-row"><summary><strong>${show(m.matchday)}ª</strong><span>${esc(statusLabel[m.status]||m.status||'—')}</span><b>${m.fantasyRating==null?'—':esc(m.fantasyRating)}</b></summary><div class="matchday-detail"><span>${esc(m.opponent||'')}</span><span>${m.rating==null?'Voto —':`Voto ${esc(m.rating)}`}</span><span>${m.minutes==null?'':`${esc(m.minutes)}′`}</span>${m.goals?`<span>${esc(m.goals)} gol</span>`:''}${m.assists?`<span>${esc(m.assists)} assist</span>`:''}${m.yellowCard?'<span>🟨</span>':''}${m.redCard?'<span>🟥</span>':''}</div></details>`).join(''):'<p class="muted">Storico giornate non ancora disponibile.</p>'}</section>`:'<div class="player-panel__empty"><strong>Statistiche non ancora disponibili</strong><p>I dati compariranno dopo il prossimo aggiornamento ufficiale.</p></div>'}</aside></div>`;
}
